#!/usr/bin/python3
import sys
from argparse import ArgumentParser

from BMPstat.bmpstat import BMPstat

def LSB_embedder_one_layer(host: BMPstat, data: bytearray, layer: int, max_sublayer: int):
	"""
		The data will be embedded in the LSB of host.
		
		- How many LSB? max_sublayer is the upper bound.
		- How many bits?
			Host data payload = host size // Bpp (1 layer) [Bytes per layer]
			Host data payload = (host size // Bpp) * max_sublayer [max bits per layer]
			Host data payload = ((host size // Bpp) * max_sublayer) // 8 [Bytes]

		Check if max_sublayer < bpp
		Check if data size * 8 (bits) < host data payload.
	"""
	host.check_layer(layer)
	host.check_sublayer(max_sublayer)

	host_data_payload = ((host.get_payload_size() // host.get_Bpp()) * max_sublayer // 8)
	data_size = len(data)

	padding = host_data_payload - data_size
	if padding < 0:
		print(f"Error@LSB_embedder_one_layer: Host data payload {host_data_payload}B < {data_size}B")
		sys.exit(1)
	
	"""
		Fill data with padding necessary to fill until max_sublayer.
	"""
	data.extend(b'\x00'*padding)

	width, height = host.get_size()
	k = 0
	for sublayer in range(max_sublayer+1): # included
		for j in range(height):
			for i in range(width):
				if data[k % data_size] & (0x1 << sublayer):
					host.set_one(i, j, layer, sublayer)
				else:
					host.set_zero(i, j, layer, sublayer)
				k+=1

def embedder(HOST: str, DATA: str, OUT: str, NO_ZEROS: bool):
	print("="*15+" Embedding "+"="*15)

	with open(DATA, "rb") as f1:
		data = f1.read()

	with open(HOST, "rb") as f2:
		"""
			Host image is BMPstat parsing
		"""
		host = BMPstat(f2.read())

	"""
		The data must to be <= data payload of the host image 
	"""
	buf_size = host.get_payload_size() + host.get_padding() # BYTES
	data_size = len(data)

	print(f"INPUT:\n\t[+] Host size: {buf_size} B\n\t[+] Data size: {data_size} B")

	padding=buf_size-data_size

	if padding < 0:
		print(f"**Error@Embedding**: the host image size < data size. The difference is {-1*padding}B")
		sys.exit(1)

	_hidden = bytearray(data)
	offset=host.get_offset()
	if not NO_ZEROS:
		"""
			Embedding with padding (NULL bytes)
		"""
		_hidden.extend(b'\x00'*padding) 
		host.set_payload(_hidden)

	else:
		"""
			Embedding without padding (Substitution)
		"""
		host.raw_image[offset: offset+data_size] = _hidden # BYPASS size check

	#else:
	# 	"""
	#		LSB embedding
	#	"""
	#	LSB_embedder_one_layer(host, _hidden, 2, 1)

	with open(OUT, "wb") as f3:
		f3.write(host.get_raw_image())

	print(f"\nOUTPUT:\n\t[+] New file {OUT}\n\t[+] offset: @{offset} B\n\t[+] padding size: {padding} B")

def get_input():
	# Command-line arguments parser
	parser = ArgumentParser(
		prog="BMPembedder", 
		description="Embedder data in BMP file.")

	parser = ArgumentParser(add_help=True)
	parser.add_argument("-i", "--host", help="Host BMP image", type=str, required=True)
	parser.add_argument("-d", "--data", help="File to embed in the host (any type) ", type=str, required=True)
	parser.add_argument("-o", "--output", help="Output filename (BMP)", type=str, required=True)
	parser.add_argument("--no-padding", help="Default padding is NULL byte, otherwise use HOST data", action="store_true", default=False, required=False)

	try:
		args = parser.parse_args()
	except SystemExit as e:
		print(e)
		
	HOST = args.host
	DATA = args.data
	OUT = args.output
	NO_ZEROS = args.no_padding

	return HOST, DATA, OUT, NO_ZEROS

if __name__ == "__main__":
	HOST, DATA, OUT, NO_ZEROS = get_input()
	embedder(HOST,DATA,OUT,NO_ZEROS)


